### ISSUE TITLE
Form Pop-ups

### ISSUE THREAD

**Issue by jessbeutler** [osmus/osmgeoweek#1]
When submitting a form:

- Pop-up warning appears that says "Please provide a valid URL. URLs need to start with "http://" or "https://"" even though URLs are not required. Form submits but this has confused WG members testing out the form.
![image](https://github.com/osmus/osmgeoweek/assets/36767434/ac4311bd-6fcd-4c28-9d03-3d4c8a1772f8)

- And not sure if this is on our side, but a popup appears after submitting warning about losing changes. Again, confusing for submitters.
![image](https://github.com/osmus/osmgeoweek/assets/36767434/234b92fd-ea59-4a6f-a3f4-a3f5e4cae7ba)

**Comment by d3netxer** [comment]
I have committed a code change that removes the validation for the url. I believe this will take care of the issue.

**Comment by d3netxer** [comment]
I have also seen the pop-up appearing when a form is partially filled and a user leaves the page. 

The pop-up we are seeing is likely a warning triggered by the browser when you attempt to navigate away from a page with a form that has unsaved changes. This is to prevent users from losing data they might have entered into form fields without submitting.

I believe that this pop-up is beneficial before a user has clicked the submit button, but not useful after the user has pressed the submit button. However, I think the pop-up is appearing in both cases.

Should the best course of action be for me to try to disable the pop-up only after a user has pressed the submit form button?

**Comment by jessbeutler** [comment]
@d3netxer Agreed that the form is helpful before the user has clicked the submit button! :) Should have clarified that it's happening after the user has pressed submit which is causing the confusion. 

Your recommended course of action is ideal!

**Comment by d3netxer** [comment]
ok cool, I implemented the change
