### ISSUE TITLE
Transfer domain name osmgeoweek.org to OSM US

### ISSUE THREAD

**Issue by quincylvania** [osmus/osmgeoweek#13]
It appears that "osmgeoweek.org" is registered at Namecheap but not by OSM US. We need to track down who owns this domain and transfer it over so there are no interruptions. Any idea, @d3netxer?

**Comment by d3netxer** [comment]
I own the domain @quincylvania. I'm happy to transfer the domain over when you are ready

**Comment by quincylvania** [comment]
@d3netxer Thanks!! I messaged you on Slack.
