### ISSUE TITLE
Post projects to OSMGeoWeek

### ISSUE THREAD

**Issue by jessbeutler** [osmus/osmgeoweek#8]
Projects to be posted no earlier than 11/6. Suggested projects can be added below, to be reviewed.

**Comment by Geocruizer** [comment]
The following projects are being managed by the Meta Open Maps Team in coordination with local organizations dedicated to improving pedestrian data in OSM.

https://tasks.mapwith.ai/projects/149
https://tasks.mapwith.ai/projects/151
https://tasks.mapwith.ai/projects/157
